
# Loop constraints
directive set /GameUnit/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /GameUnit/core/core:rlp/main CSTEPS_FROM {{. == 10} {.. == 0}}

# IO operation constraints
directive set /GameUnit/core/core:rlp/main/random:io_read(random:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/redobjecty:io_read(redobjecty:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/blueobjecty:io_read(blueobjecty:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/meteorpx:io_read(meteorpx:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/meteorpy:io_read(meteorpy:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/meteordirectionin:io_read(meteordirectionin:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/p1planets:io_read(p1planets:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/p2planets:io_read(p2planets:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/io_read(restart:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:io_write(player2score:rsc.d)#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:io_write(player1score:rsc.d)#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/io_write(player1y:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/io_write(player2y:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/io_write(meteorpxout:rsc.d) CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/io_write(meteorpyout:rsc.d) CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/io_write(meteordirectionout:rsc.d) CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p1:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p2:rsc.d) CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p3:rsc.d) CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p4:rsc.d) CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p5:rsc.d) CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p6:rsc.d) CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p7:rsc.d) CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/io_write(p1p8:rsc.d) CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p1:rsc.d) CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p2:rsc.d) CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p3:rsc.d) CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p4:rsc.d) CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p5:rsc.d) CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p6:rsc.d) CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p7:rsc.d) CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/io_write(p2p8:rsc.d) CSTEPS_FROM {{.. == 8}}

# Real operation constraints
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:if:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:if:if:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:if:if:unequal CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:if:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:else:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:else:if:equal CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:else:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision:if:mux CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:unequal CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:if:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:else:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:else:if:equal CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:else:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:else:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:else:if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#1:if:mux CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:if:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:unequal CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:if:if:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:else:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:else:if:equal CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:else:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:else:if:acc CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:else:if:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:else:if:acc#3 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#2:if:mux CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#9 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#8 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#10 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#11 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#12 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:if:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:unequal CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:if:if:acc#3 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:else:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:else:if:equal CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:else:if:acc#3 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:else:if:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:else:if:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:else:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#3:if:mux CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:if:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:unequal CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:if:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:else:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:else:if:equal CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:else:if:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:else:if:acc CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:else:if:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:else:if:acc#3 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#4:if:mux CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:acc#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:unequal CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:acc#6 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:acc#7 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:if:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:else:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:else:if:equal CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:else:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:else:if:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:else:if:acc#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:else:if:acc#3 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#5:if:mux CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:acc#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:unequal CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:acc#6 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:acc#7 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:if:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:else:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:else:if:equal CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:else:if:acc#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:else:if:acc CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:else:if:acc#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:else:if:acc#3 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#6:if:mux CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:unequal CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:acc#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:acc#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:if:if:acc#3 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:else:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:else:if:equal CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:else:if:acc#3 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:else:if:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:else:if:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:else:if:acc#2 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#7:if:mux CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#8:if:else:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#8:if:else:if:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#8:if:else:if:equal CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#8:if:else:if:acc#3 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:if:acc CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:if:equal CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:if:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:if:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#9:if:else:if:acc#3 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:if:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:if:equal CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:if:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:if:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:if:acc#6 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#10:if:else:if:acc#4 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:if:acc CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:if:equal CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:if:acc#4 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:if:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:if:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#11:if:else:if:acc#3 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:if:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:if:equal CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:if:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:if:acc#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#12:if:else:if:acc#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:if:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:if:equal CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:if:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:if:acc#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#13:if:else:if:acc#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:if:acc CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:if:equal CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:if:acc#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:if:acc#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#14:if:else:if:acc#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:acc CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:if:acc CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:if:equal CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:if:acc#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:if:acc#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/planet_meteor_collision#15:if:else:if:acc#3 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:mux#1 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#46 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux1h#3 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#12 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#16 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#20 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#24 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#28 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#32 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#35 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#41 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#47 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#53 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#59 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#65 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#71 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux#77 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux1h#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#13 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#17 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#21 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#25 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#29 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#33 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#36 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#42 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#48 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#54 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#60 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#66 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#72 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux#78 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#14 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#18 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#22 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#26 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#30 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#34 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#37 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#43 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#49 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#55 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#61 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#67 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#73 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux#79 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc#6 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:if:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:else:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision:mux CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#5 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#51 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#52 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#11 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:else:else:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:else:and CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc#6 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:if:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:else:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#1:mux CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#5 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#54 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#55 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#11 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision:oelse:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:else:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:else:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:else:else:else:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:else:else:and CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc#6 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:if:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:else:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#2:mux CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#5 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#57 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#58 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#11 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision#1:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision#1:oelse:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:else:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:else:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:else:else:else:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:else:else:and CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:if:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#5 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#60 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#61 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:else:else:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:if:else:and CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:if:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#5 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#63 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#64 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision#2:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision#2:oelse:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:else:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:else:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:else:else:else:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:if:else:else:and CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:if:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:if:equal CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:if:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:if:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:if:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#4 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#3 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#5 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#66 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/acc#67 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision#3:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/wall_meteor_collision#3:oelse:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:else:else:if:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:else:else:if:acc#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:else:else:else:acc CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:if:else:else:and CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#7 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#6 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#9 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#5 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#4 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#8 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#10 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#11 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#12 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#2 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc#13 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:else:acc CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/mux#18 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/mux#20 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/mux1h CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/mux1h#1 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:mux#15 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:mux#20 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:mux#29 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:mux#38 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:mux#235 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:mux#6 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:mux#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:mux#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:mux#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:mux#16 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:mux#21 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:mux#30 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:mux#39 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:mux#236 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:mux#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:mux#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:mux#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:mux#7 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:mux#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:mux#9 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:mux#11 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:mux#17 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:mux#22 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:mux#31 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:mux#40 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:mux#237 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:if#1:mux#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:if:mux#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:if:mux#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#3:else:mux#8 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#4:else:mux#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/ship_meteor_collision#5:else:mux#10 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:else:mux#12 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:else:mux#18 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:else:mux#23 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:else:mux#32 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else#1:mux#41 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:mux#238 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#3 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:mux#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#3 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#4 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:mux#5 CSTEPS_FROM {{.. == 2}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#3 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:mux#6 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#4 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#5 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#6 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:mux#7 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 3}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#7 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:mux#8 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#7 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#8 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:mux#9 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#7 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#8 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#9 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:mux#10 CSTEPS_FROM {{.. == 4}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#8 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#9 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#10 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:mux#11 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#9 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#10 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#11 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:mux#12 CSTEPS_FROM {{.. == 5}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#10 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#11 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#12 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:mux#13 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#10 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#11 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#12 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#13 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:mux#14 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 6}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#12 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#13 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#14 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:mux#15 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#12 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#13 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#14 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#15 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:mux#16 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#3 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#4 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#5 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#6 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#7 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#8 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#9 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#10 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#11 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#12 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#13 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#14 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#15 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#16 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux#17 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/mux1h#2 CSTEPS_FROM {{.. == 9}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#20 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#30 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#40 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#50 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#60 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#70 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#80 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#90 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#99 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#112 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#121 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#134 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#147 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#160 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#173 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux#186 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/mux#372 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#22 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#32 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:else:mux#42 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:else:mux#52 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:else:mux#62 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:else:mux#72 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:else:mux#82 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:else:mux#92 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:else:mux#101 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:else:mux#114 CSTEPS_FROM {{.. == 7}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:else:mux#123 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:else:mux#136 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:else:mux#149 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:else:mux#162 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:else:mux#175 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/else:mux#188 CSTEPS_FROM {{.. == 8}}
directive set /GameUnit/core/core:rlp/main/mux#374 CSTEPS_FROM {{.. == 8}}
