directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else#1:else:else:if:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(1,0,1,0,2)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:if:if:unequal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:if:if:unequal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:if:if:unequal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:if:if:unequal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:if:if:unequal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:else:if:equal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:else:if:equal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:else:if:equal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(2)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:else:if:equal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(2)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:else:if:equal RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_equal(2)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else#1:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision#3:else:if:acc#8 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else#1:else:else:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#2:if:else:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:else:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision:else:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#11:if:else:if:acc#5 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#2:if:if:if:acc#8 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:if:if:acc#10 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:if:if:acc#11 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#9:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#13:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#15:if:else:if:acc#5 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:if:if:acc#12 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:if:if:acc#13 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#9:if:else:if:acc#5 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#13:if:else:if:acc#6 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#14:if:else:if:acc#6 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#2:if:if:if:acc#12 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#10:if:else:if:acc#6 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#1:if:if:if:acc#11 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:if:if:acc#7 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:if:if:acc#11 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:if:if:acc#10 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#11:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#12:if:else:if:acc#6 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#15:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:if:if:acc#8 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#6
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:if:if:acc#13 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#6
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:if:if:acc#12 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#6
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#10:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#6
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#12:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#6
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#14:if:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,13)#6
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:else:if:acc#3 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:if:if:acc#4 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#9:if:else:if:acc#3 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#12:if:else:if:acc#4 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#14:if:else:if:acc#4 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#1:if:if:if:acc#9 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:if:if:acc#14 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:if:if:acc#15 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:if:if:acc#14 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#10:if:else:if:acc#4 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#13:if:else:if:acc#4 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#15:if:else:if:acc#3 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#2:if:if:if:acc#14 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:if:if:acc#15 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#11:if:else:if:acc#3 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(12,0,12,1,13)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#14 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#22 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#18 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#16 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#20 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#14 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#20 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#16 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#20 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#22 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#14 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#12 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#28 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#28 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#26 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,0,3)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#18 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#12 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#16 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#16 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#24 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#18 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#22 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#13 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:if:acc#13 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:if:acc#13 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#13 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else#1:if:if:acc RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#2 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:if:acc#2 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:else:else:else:else:else:else:else:else:else:else:else:if:acc#2 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#3
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#30 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#30 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#28 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#4
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#32 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#30 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)#5
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#2 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/acc#52 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#26 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,5)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#26 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,5)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if#1:if:acc#24 RESOURCE_NAME else:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,5)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,1,5)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else:else:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,1,5)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/acc#51 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,1,5)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#2:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#1:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision:if:if:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/else:else#1:if:if:acc#12 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(2,0,2,1,3)#2
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision#3:else:if:acc#16 RESOURCE_NAME ship_meteor_collision#3:else:if:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision#3:else:if:acc#14 RESOURCE_NAME ship_meteor_collision#3:else:if:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision:if:if:acc#20 RESOURCE_NAME ship_meteor_collision:if:if:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision:if:if:acc#18 RESOURCE_NAME ship_meteor_collision:if:if:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#2:if:if:if:acc#10 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(13,0,12,0,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#4:if:if:if:acc#10 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(13,0,12,0,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/ship_meteor_collision:if:if:acc#10 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(13,0,12,0,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/wall_meteor_collision:if:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(13,0,12,0,13)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision:if:if:if:acc#5 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(13,0,12,0,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#8:if:else:if:acc#3 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(13,0,12,0,13)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#3:if:if:if:acc#8 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#6:if:if:if:acc#9 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#11:if:else:if:acc#6 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#14:if:else:if:acc#7 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,0,3)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#5:if:if:if:acc#9 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#7:if:if:if:acc#8 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#13:if:else:if:acc#7 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#15:if:else:if:acc#6 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(4,0,4,0,4)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#9:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#11:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#13:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#15:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#8:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#10:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)#1
directive set /GameUnit/GameUnit:core/GameUnit:core:conc/planet_meteor_collision#14:if:else:if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(5,0,1,1,6)#1
