// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   apl115@EEWS104A-017
//  Generated date: Tue May 10 13:31:42 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    blueobject_core
// ------------------------------------------------------------------


module blueobject_core (
  clk, rst, VGA_VS_rsc_mgc_in_wire_d, vga_xy_rsc_mgc_in_wire_d, video_in_rsc_mgc_in_wire_d,
      player2y_rsc_mgc_out_stdreg_d
);
  input clk;
  input rst;
  input VGA_VS_rsc_mgc_in_wire_d;
  input [19:0] vga_xy_rsc_mgc_in_wire_d;
  input [29:0] video_in_rsc_mgc_in_wire_d;
  output [9:0] player2y_rsc_mgc_out_stdreg_d;
  reg [9:0] player2y_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg findpixelblue_sva;
    reg [9:0] blueobjy_sva;
    reg [27:0] io_read_video_in_rsc_d_1_cse_sg1_sva;
    reg [9:0] vga_y_sva;
    reg findpixelblue_sva_dfm;
    reg slc_svs;
    reg land_1_sva_1;
    reg land_1_lpi_1_dfm;
    reg land_sva_1;
    reg land_lpi_1_dfm;

    begin : core_rlpExit
      forever begin : core_rlp
        // C-Step 0 of Loop 'core_rlp'
        findpixelblue_sva = 1'b0;
        blueobjy_sva = 10'b0;
        begin : mainExit
          forever begin : main
            // C-Step 0 of Loop 'main'
            begin : waitLoop0Exit
              forever begin : waitLoop0
                @(posedge clk);
                if ( rst )
                  disable core_rlpExit;
                if ( clk )
                  disable waitLoop0Exit;
              end
            end
            // C-Step 1 of Loop 'main'
            land_sva_1 = 1'b0;
            land_1_sva_1 = 1'b0;
            io_read_video_in_rsc_d_1_cse_sg1_sva = video_in_rsc_mgc_in_wire_d[29:2];
            vga_y_sva = (vga_xy_rsc_mgc_in_wire_d[19:10]) + 10'b1111011101;
            findpixelblue_sva_dfm = findpixelblue_sva | VGA_VS_rsc_mgc_in_wire_d;
            slc_svs = readslicef_11_1_10((({1'b1 , (~ (io_read_video_in_rsc_d_1_cse_sg1_sva[27:18]))})
                + 11'b110010001));
            if ( slc_svs ) begin
            end
            else begin
              land_1_sva_1 = ~ (readslicef_11_1_10((({1'b1 , (~ (io_read_video_in_rsc_d_1_cse_sg1_sva[17:8]))})
                  + 11'b110010001)));
            end
            land_1_lpi_1_dfm = land_1_sva_1 & (~ slc_svs);
            if ( land_1_lpi_1_dfm ) begin
              land_sva_1 = ~ (readslicef_9_1_8((conv_u2u_8_9(io_read_video_in_rsc_d_1_cse_sg1_sva[7:0])
                  + 9'b110000011)));
            end
            land_lpi_1_dfm = land_sva_1 & land_1_lpi_1_dfm;
            if ( land_lpi_1_dfm ) begin
              player2y_rsc_mgc_out_stdreg_d <= MUX_v_10_2_2({blueobjy_sva , vga_y_sva},
                  findpixelblue_sva_dfm);
            end
            findpixelblue_sva = findpixelblue_sva_dfm & (~ land_lpi_1_dfm);
            blueobjy_sva = MUX_v_10_2_2({blueobjy_sva , vga_y_sva}, findpixelblue_sva_dfm
                & land_lpi_1_dfm);
            begin : waitLoop1Exit
              forever begin : waitLoop1
                @(posedge clk);
                if ( rst )
                  disable core_rlpExit;
                if ( clk )
                  disable waitLoop1Exit;
              end
            end
            // C-Step 2 of Loop 'main'
          end
        end
      end
    end
    land_lpi_1_dfm = 1'b0;
    land_sva_1 = 1'b0;
    land_1_lpi_1_dfm = 1'b0;
    land_1_sva_1 = 1'b0;
    slc_svs = 1'b0;
    findpixelblue_sva_dfm = 1'b0;
    vga_y_sva = 10'b0;
    io_read_video_in_rsc_d_1_cse_sg1_sva = 28'b0;
    blueobjy_sva = 10'b0;
    findpixelblue_sva = 1'b0;
    player2y_rsc_mgc_out_stdreg_d <= 10'b0;
  end


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_9_1_8;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_9_1_8 = tmp[0:0];
  end
  endfunction


  function [9:0] MUX_v_10_2_2;
    input [19:0] inputs;
    input [0:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[19:10];
      end
      1'b1 : begin
        result = inputs[9:0];
      end
      default : begin
        result = inputs[19:10];
      end
    endcase
    MUX_v_10_2_2 = result;
  end
  endfunction


  function  [8:0] conv_u2u_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_9 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    blueobject
//  Generated from file(s):
//    2) $PROJECT_HOME/vga_mouse_square.c
// ------------------------------------------------------------------


module blueobject (
  VGA_VS_rsc_z, vga_xy_rsc_z, video_in_rsc_z, player2y_rsc_z, clk, rst
);
  input VGA_VS_rsc_z;
  input [19:0] vga_xy_rsc_z;
  input [29:0] video_in_rsc_z;
  output [9:0] player2y_rsc_z;
  input clk;
  input rst;


  // Interconnect Declarations
  wire VGA_VS_rsc_mgc_in_wire_d;
  wire [19:0] vga_xy_rsc_mgc_in_wire_d;
  wire [29:0] video_in_rsc_mgc_in_wire_d;
  wire [9:0] player2y_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(1)) VGA_VS_rsc_mgc_in_wire (
      .d(VGA_VS_rsc_mgc_in_wire_d),
      .z(VGA_VS_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(20)) vga_xy_rsc_mgc_in_wire (
      .d(vga_xy_rsc_mgc_in_wire_d),
      .z(vga_xy_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(30)) video_in_rsc_mgc_in_wire (
      .d(video_in_rsc_mgc_in_wire_d),
      .z(video_in_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(10)) player2y_rsc_mgc_out_stdreg (
      .d(player2y_rsc_mgc_out_stdreg_d),
      .z(player2y_rsc_z)
    );
  blueobject_core blueobject_core_inst (
      .clk(clk),
      .rst(rst),
      .VGA_VS_rsc_mgc_in_wire_d(VGA_VS_rsc_mgc_in_wire_d),
      .vga_xy_rsc_mgc_in_wire_d(vga_xy_rsc_mgc_in_wire_d),
      .video_in_rsc_mgc_in_wire_d(video_in_rsc_mgc_in_wire_d),
      .player2y_rsc_mgc_out_stdreg_d(player2y_rsc_mgc_out_stdreg_d)
    );
endmodule



