// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   apl115@EEWS104A-012
//  Generated date: Fri May 06 12:24:47 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    ImageUnit_core
// ------------------------------------------------------------------


module ImageUnit_core (
  clk, en, arst_n, vga_x_rsc_mgc_in_wire_d, vga_y_rsc_mgc_in_wire_d, p1y_rsc_mgc_in_wire_d,
      p2y_rsc_mgc_in_wire_d, bx_rsc_mgc_in_wire_d, by_rsc_mgc_in_wire_d, p1planets_rsc_mgc_in_wire_d,
      p2planets_rsc_mgc_in_wire_d, RGB_rsc_mgc_in_wire_d, RGB_o_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  input [10:0] vga_x_rsc_mgc_in_wire_d;
  input [10:0] vga_y_rsc_mgc_in_wire_d;
  input [10:0] p1y_rsc_mgc_in_wire_d;
  input [10:0] p2y_rsc_mgc_in_wire_d;
  input [10:0] bx_rsc_mgc_in_wire_d;
  input [10:0] by_rsc_mgc_in_wire_d;
  input [7:0] p1planets_rsc_mgc_in_wire_d;
  input [7:0] p2planets_rsc_mgc_in_wire_d;
  input [29:0] RGB_rsc_mgc_in_wire_d;
  output [29:0] RGB_o_rsc_mgc_out_stdreg_d;
  reg [29:0] RGB_o_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [10:0] vga_x_1_sva;
    reg [10:0] vga_y_1_sva;
    reg [10:0] p1y_1_sva;
    reg [10:0] p2y_1_sva;
    reg [10:0] bx_1_sva;
    reg [10:0] by_1_sva;
    reg [7:0] p1planets_1_sva;
    reg [7:0] p2planets_1_sva;
    reg slc_svs;
    reg land_2_sva_1;
    reg land_2_lpi_dfm;
    reg land_1_sva_1;
    reg land_1_lpi_dfm;
    reg land_sva_1;
    reg land_lpi_dfm;
    reg else_slc_svs;
    reg else_land_2_sva_1;
    reg else_land_2_lpi_dfm;
    reg else_land_1_sva_1;
    reg else_land_1_lpi_dfm;
    reg else_land_sva_1;
    reg else_land_lpi_dfm;
    reg else_else_slc_svs;
    reg else_else_land_2_sva_1;
    reg else_else_land_2_lpi_dfm;
    reg else_else_land_1_sva_1;
    reg else_else_land_1_lpi_dfm;
    reg else_else_land_sva_1;
    reg else_else_land_lpi_dfm;
    reg else_else_else_slc_svs;
    reg else_else_else_land_sva_1;
    reg else_else_else_land_lpi_dfm;
    reg else_else_else_if_land_1_sva_1;
    reg else_else_else_if_land_1_lpi_dfm;
    reg else_else_else_if_land_sva_1;
    reg else_else_else_if_land_lpi_dfm;
    reg else_else_else_if_else_land_1_sva_1;
    reg else_else_else_if_else_land_1_lpi_dfm;
    reg else_else_else_if_else_land_sva_1;
    reg else_else_else_if_else_land_lpi_dfm;
    reg else_else_else_if_else_else_land_1_sva_1;
    reg else_else_else_if_else_else_land_1_lpi_dfm;
    reg else_else_else_if_else_else_land_sva_1;
    reg else_else_else_if_else_else_land_lpi_dfm;
    reg else_else_else_if_else_else_else_land_1_sva_1;
    reg else_else_else_if_else_else_else_land_1_lpi_dfm;
    reg else_else_else_if_else_else_else_land_sva_1;
    reg else_else_else_if_else_else_else_land_lpi_dfm;
    reg else_else_else_if_else_else_else_else_land_1_sva_1;
    reg else_else_else_if_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_if_else_else_else_else_land_sva_1;
    reg else_else_else_if_else_else_else_else_land_lpi_dfm;
    reg else_else_else_if_else_else_else_else_else_land_1_sva_1;
    reg else_else_else_if_else_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_if_else_else_else_else_else_land_sva_1;
    reg else_else_else_if_else_else_else_else_else_land_lpi_dfm;
    reg else_else_else_if_else_else_else_else_else_else_land_1_sva_1;
    reg else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_if_else_else_else_else_else_else_land_sva_1;
    reg else_else_else_if_else_else_else_else_else_else_land_lpi_dfm;
    reg else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1;
    reg else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_if_else_else_else_else_else_else_else_land_sva_1;
    reg else_else_else_else_slc_svs;
    reg else_else_else_else_land_sva_1;
    reg else_else_else_else_land_lpi_dfm;
    reg else_else_else_else_if_land_1_sva_1;
    reg else_else_else_else_if_land_1_lpi_dfm;
    reg else_else_else_else_if_land_sva_1;
    reg else_else_else_else_if_land_lpi_dfm;
    reg else_else_else_else_if_else_land_1_sva_1;
    reg else_else_else_else_if_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_land_sva_1;
    reg else_else_else_else_if_else_land_lpi_dfm;
    reg else_else_else_else_if_else_else_land_1_sva_1;
    reg else_else_else_else_if_else_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_else_land_sva_1;
    reg else_else_else_else_if_else_else_land_lpi_dfm;
    reg else_else_else_else_if_else_else_else_land_1_sva_1;
    reg else_else_else_else_if_else_else_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_else_else_land_sva_1;
    reg else_else_else_else_if_else_else_else_land_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_land_1_sva_1;
    reg else_else_else_else_if_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_land_sva_1;
    reg else_else_else_else_if_else_else_else_else_land_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_else_land_1_sva_1;
    reg else_else_else_else_if_else_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_else_land_sva_1;
    reg else_else_else_else_if_else_else_else_else_else_land_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_else_else_land_1_sva_1;
    reg else_else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_else_else_land_sva_1;
    reg else_else_else_else_if_else_else_else_else_else_else_land_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1;
    reg else_else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm;
    reg else_else_else_else_if_else_else_else_else_else_else_else_land_sva_1;
    reg else_else_else_else_if_else_else_else_else_else_else_else_land_lpi_dfm;
    reg [29:0] C1047552_30_dfmergedata_sva_19;
    reg [29:0] C1047552_30_dfmergedata_lpi_dfm_20;
    reg nor_m1c;
    reg else_else_else_if_or_4_tmp;
    reg else_else_and_m1c;
    reg else_else_else_else_if_or_tmp;
    reg else_else_else_and_m1c;
    reg and_itm;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        else_land_sva_1 = 1'b0;
        else_land_1_sva_1 = 1'b0;
        else_land_2_sva_1 = 1'b0;
        land_sva_1 = 1'b0;
        land_1_sva_1 = 1'b0;
        land_2_sva_1 = 1'b0;
        vga_x_1_sva = vga_x_rsc_mgc_in_wire_d;
        vga_y_1_sva = vga_y_rsc_mgc_in_wire_d;
        p1y_1_sva = p1y_rsc_mgc_in_wire_d;
        p2y_1_sva = p2y_rsc_mgc_in_wire_d;
        slc_svs = readslicef_12_1_11((conv_u2s_11_12(vga_x_1_sva) + 12'b111101111111));
        if ( slc_svs ) begin
        end
        else begin
          land_2_sva_1 = ~ (readslicef_11_1_10((({1'b1 , (~ (vga_x_1_sva[10:1]))})
              + 11'b1010101)));
        end
        land_2_lpi_dfm = land_2_sva_1 & (~ slc_svs);
        if ( land_2_lpi_dfm ) begin
          land_1_sva_1 = ~ (readslicef_13_1_12((conv_u2u_12_13(conv_u2u_11_12(vga_y_1_sva)
              + conv_u2u_11_12(~ p1y_1_sva)) + 13'b1100000110011)));
        end
        land_1_lpi_dfm = land_1_sva_1 & land_2_lpi_dfm;
        if ( land_1_lpi_dfm ) begin
          land_sva_1 = ~ (readslicef_13_1_12((conv_u2u_12_13(conv_u2u_11_12(p1y_1_sva)
              + conv_u2u_11_12(~ vga_y_1_sva)) + 13'b1100000110011)));
        end
        land_lpi_dfm = land_sva_1 & land_1_lpi_dfm;
        if ( land_lpi_dfm ) begin
        end
        else begin
          else_slc_svs = readslicef_12_1_11((conv_u2s_11_12(vga_x_1_sva) + 12'b101111010011));
          if ( else_slc_svs ) begin
          end
          else begin
            else_land_2_sva_1 = ~ (readslicef_10_1_9((conv_u2s_9_10(~ (vga_x_1_sva[9:1]))
                + 10'b1000101011)));
          end
          else_land_2_lpi_dfm = else_land_2_sva_1 & (~ else_slc_svs);
          if ( else_land_2_lpi_dfm ) begin
            else_land_1_sva_1 = ~ (readslicef_13_1_12((conv_u2u_12_13(conv_u2u_11_12(vga_y_1_sva)
                + conv_u2u_11_12(~ p2y_1_sva)) + 13'b1100000110011)));
          end
          else_land_1_lpi_dfm = else_land_1_sva_1 & else_land_2_lpi_dfm;
          if ( else_land_1_lpi_dfm ) begin
            else_land_sva_1 = ~ (readslicef_13_1_12((conv_u2u_12_13(conv_u2u_11_12(p2y_1_sva)
                + conv_u2u_11_12(~ vga_y_1_sva)) + 13'b1100000110011)));
          end
          else_land_lpi_dfm = else_land_sva_1 & else_land_1_lpi_dfm;
        end
        begin : waitLoop1Exit
          forever begin : waitLoop1
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop1Exit;
          end
        end
        // C-Step 2 of Loop 'main'
        else_else_land_lpi_dfm = 1'b0;
        else_else_else_if_land_lpi_dfm = 1'b0;
        else_else_else_land_lpi_dfm = 1'b0;
        else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_if_land_sva_1 = 1'b0;
        else_else_else_if_land_1_sva_1 = 1'b0;
        else_else_else_land_sva_1 = 1'b0;
        else_else_land_sva_1 = 1'b0;
        else_else_land_1_sva_1 = 1'b0;
        else_else_land_2_sva_1 = 1'b0;
        bx_1_sva = bx_rsc_mgc_in_wire_d;
        by_1_sva = by_rsc_mgc_in_wire_d;
        p1planets_1_sva = p1planets_rsc_mgc_in_wire_d;
        p2planets_1_sva = p2planets_rsc_mgc_in_wire_d;
        if ( land_lpi_dfm ) begin
        end
        else if ( else_land_lpi_dfm ) begin
        end
        else begin
          else_else_slc_svs = readslicef_9_1_8((conv_u2u_8_9(readslicef_12_8_4((conv_u2u_11_12(vga_x_1_sva)
              + conv_u2u_11_12(~ bx_1_sva)))) + 9'b110000001));
          if ( else_else_slc_svs ) begin
          end
          else begin
            else_else_land_2_sva_1 = ~ (readslicef_9_1_8((conv_u2u_8_9(readslicef_12_8_4((conv_u2u_11_12(bx_1_sva)
                + conv_u2u_11_12(~ vga_x_1_sva)))) + 9'b110000001)));
          end
          else_else_land_2_lpi_dfm = else_else_land_2_sva_1 & (~ else_else_slc_svs);
          if ( else_else_land_2_lpi_dfm ) begin
            else_else_land_1_sva_1 = ~ (readslicef_9_1_8((conv_u2u_8_9(readslicef_12_8_4((conv_u2u_11_12(vga_y_1_sva)
                + conv_u2u_11_12(~ by_1_sva)))) + 9'b110000001)));
          end
          else_else_land_1_lpi_dfm = else_else_land_1_sva_1 & else_else_land_2_lpi_dfm;
          if ( else_else_land_1_lpi_dfm ) begin
            else_else_land_sva_1 = ~ (readslicef_9_1_8((conv_u2u_8_9(readslicef_12_8_4((conv_u2u_11_12(by_1_sva)
                + conv_u2u_11_12(~ vga_y_1_sva)))) + 9'b110000001)));
          end
          else_else_land_lpi_dfm = else_else_land_sva_1 & else_else_land_1_lpi_dfm;
          if ( else_else_land_lpi_dfm ) begin
          end
          else begin
            else_else_else_slc_svs = readslicef_12_1_11((conv_u2s_11_12(vga_x_1_sva)
                + 12'b111111101101));
            if ( else_else_else_slc_svs ) begin
            end
            else begin
              else_else_else_land_sva_1 = ~ (readslicef_8_1_7((({1'b1 , (~ (vga_x_1_sva[10:4]))})
                  + 8'b101)));
            end
            else_else_else_land_lpi_dfm = else_else_else_land_sva_1 & (~ else_else_else_slc_svs);
            if ( else_else_else_land_lpi_dfm ) begin
              if ( p1planets_1_sva[0] ) begin
                else_else_else_if_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                    + 12'b111111111101)));
              end
              else_else_else_if_land_1_lpi_dfm = else_else_else_if_land_1_sva_1 &
                  (p1planets_1_sva[0]);
              if ( else_else_else_if_land_1_lpi_dfm ) begin
                else_else_else_if_land_sva_1 = ~ (readslicef_10_1_9((({1'b1 , (~
                    (vga_y_1_sva[10:2]))}) + 10'b11111)));
              end
              else_else_else_if_land_lpi_dfm = else_else_else_if_land_sva_1 & else_else_else_if_land_1_lpi_dfm;
            end
            else begin
              else_else_else_else_slc_svs = readslicef_8_1_7((conv_u2u_7_8(vga_x_1_sva[10:4])
                  + 8'b10110101));
              if ( else_else_else_else_slc_svs ) begin
              end
              else begin
                else_else_else_else_land_sva_1 = ~ (readslicef_11_1_10((conv_u2s_10_11(~
                    (vga_x_1_sva[9:0])) + 11'b10011101101)));
              end
              else_else_else_else_land_lpi_dfm = else_else_else_else_land_sva_1 &
                  (~ else_else_else_else_slc_svs);
            end
          end
        end
        nor_m1c = ~(else_land_lpi_dfm | land_lpi_dfm);
        else_else_and_m1c = else_else_else_land_lpi_dfm & (~ else_else_land_lpi_dfm)
            & nor_m1c;
        else_else_else_and_m1c = else_else_else_else_land_lpi_dfm & (~ else_else_else_land_lpi_dfm)
            & (~ else_else_land_lpi_dfm) & nor_m1c;
        and_itm = (~(else_else_else_else_land_lpi_dfm | else_else_else_land_lpi_dfm
            | else_else_land_lpi_dfm)) & nor_m1c;
        begin : waitLoop2Exit
          forever begin : waitLoop2
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop2Exit;
          end
        end
        // C-Step 3 of Loop 'main'
        else_else_else_else_if_else_land_lpi_dfm = 1'b0;
        else_else_else_else_if_else_else_else_land_lpi_dfm = 1'b0;
        else_else_else_else_if_else_else_else_else_else_land_lpi_dfm = 1'b0;
        else_else_else_if_else_land_lpi_dfm = 1'b0;
        else_else_else_if_else_else_else_land_lpi_dfm = 1'b0;
        else_else_else_if_else_else_else_else_else_land_lpi_dfm = 1'b0;
        else_else_else_else_if_else_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_else_if_else_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_else_land_1_sva_1 = 1'b0;
        else_else_else_else_if_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_land_1_sva_1 = 1'b0;
        else_else_else_else_if_land_sva_1 = 1'b0;
        else_else_else_else_if_land_1_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_if_else_else_else_land_sva_1 = 1'b0;
        else_else_else_if_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_if_else_else_land_sva_1 = 1'b0;
        else_else_else_if_else_else_land_1_sva_1 = 1'b0;
        else_else_else_if_else_land_sva_1 = 1'b0;
        else_else_else_if_else_land_1_sva_1 = 1'b0;
        if ( land_lpi_dfm ) begin
        end
        else if ( else_land_lpi_dfm ) begin
        end
        else if ( else_else_land_lpi_dfm ) begin
        end
        else if ( else_else_else_land_lpi_dfm ) begin
          if ( else_else_else_if_land_lpi_dfm ) begin
          end
          else begin
            if ( p1planets_1_sva[1] ) begin
              else_else_else_if_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                  + 12'b111101111101)));
            end
            else_else_else_if_else_land_1_lpi_dfm = else_else_else_if_else_land_1_sva_1
                & (p1planets_1_sva[1]);
            if ( else_else_else_if_else_land_1_lpi_dfm ) begin
              else_else_else_if_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1 ,
                  (~ (vga_y_1_sva[10:2]))}) + 10'b111111)));
            end
            else_else_else_if_else_land_lpi_dfm = else_else_else_if_else_land_sva_1
                & else_else_else_if_else_land_1_lpi_dfm;
            if ( else_else_else_if_else_land_lpi_dfm ) begin
            end
            else begin
              if ( p1planets_1_sva[2] ) begin
                else_else_else_if_else_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                    + 12'b111011111101)));
              end
              else_else_else_if_else_else_land_1_lpi_dfm = else_else_else_if_else_else_land_1_sva_1
                  & (p1planets_1_sva[2]);
              if ( else_else_else_if_else_else_land_1_lpi_dfm ) begin
                else_else_else_if_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                    , (~ (vga_y_1_sva[10:2]))}) + 10'b1011111)));
              end
              else_else_else_if_else_else_land_lpi_dfm = else_else_else_if_else_else_land_sva_1
                  & else_else_else_if_else_else_land_1_lpi_dfm;
              if ( else_else_else_if_else_else_land_lpi_dfm ) begin
              end
              else begin
                if ( p1planets_1_sva[3] ) begin
                  else_else_else_if_else_else_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                      + 12'b111001111101)));
                end
                else_else_else_if_else_else_else_land_1_lpi_dfm = else_else_else_if_else_else_else_land_1_sva_1
                    & (p1planets_1_sva[3]);
                if ( else_else_else_if_else_else_else_land_1_lpi_dfm ) begin
                  else_else_else_if_else_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                      , (~ (vga_y_1_sva[10:2]))}) + 10'b1111111)));
                end
                else_else_else_if_else_else_else_land_lpi_dfm = else_else_else_if_else_else_else_land_sva_1
                    & else_else_else_if_else_else_else_land_1_lpi_dfm;
                if ( else_else_else_if_else_else_else_land_lpi_dfm ) begin
                end
                else begin
                  if ( p1planets_1_sva[4] ) begin
                    else_else_else_if_else_else_else_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                        + 12'b110111111101)));
                  end
                  else_else_else_if_else_else_else_else_land_1_lpi_dfm = else_else_else_if_else_else_else_else_land_1_sva_1
                      & (p1planets_1_sva[4]);
                  if ( else_else_else_if_else_else_else_else_land_1_lpi_dfm ) begin
                    else_else_else_if_else_else_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                        , (~ (vga_y_1_sva[10:2]))}) + 10'b10011111)));
                  end
                  else_else_else_if_else_else_else_else_land_lpi_dfm = else_else_else_if_else_else_else_else_land_sva_1
                      & else_else_else_if_else_else_else_else_land_1_lpi_dfm;
                  if ( else_else_else_if_else_else_else_else_land_lpi_dfm ) begin
                  end
                  else begin
                    if ( p1planets_1_sva[5] ) begin
                      else_else_else_if_else_else_else_else_else_land_1_sva_1 = ~
                          (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva) + 12'b110101111101)));
                    end
                    else_else_else_if_else_else_else_else_else_land_1_lpi_dfm = else_else_else_if_else_else_else_else_else_land_1_sva_1
                        & (p1planets_1_sva[5]);
                    if ( else_else_else_if_else_else_else_else_else_land_1_lpi_dfm
                        ) begin
                      else_else_else_if_else_else_else_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                          , (~ (vga_y_1_sva[10:2]))}) + 10'b10111111)));
                    end
                    else_else_else_if_else_else_else_else_else_land_lpi_dfm = else_else_else_if_else_else_else_else_else_land_sva_1
                        & else_else_else_if_else_else_else_else_else_land_1_lpi_dfm;
                    if ( else_else_else_if_else_else_else_else_else_land_lpi_dfm
                        ) begin
                    end
                    else begin
                      if ( p1planets_1_sva[6] ) begin
                        else_else_else_if_else_else_else_else_else_else_land_1_sva_1
                            = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                            + 12'b110011111101)));
                      end
                      else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm
                          = else_else_else_if_else_else_else_else_else_else_land_1_sva_1
                          & (p1planets_1_sva[6]);
                      if ( else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm
                          ) begin
                        else_else_else_if_else_else_else_else_else_else_land_sva_1
                            = ~ (readslicef_10_1_9((({1'b1 , (~ (vga_y_1_sva[10:2]))})
                            + 10'b11011111)));
                      end
                      else_else_else_if_else_else_else_else_else_else_land_lpi_dfm
                          = else_else_else_if_else_else_else_else_else_else_land_sva_1
                          & else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm;
                    end
                  end
                end
              end
            end
          end
        end
        else if ( else_else_else_else_land_lpi_dfm ) begin
          if ( p2planets_1_sva[0] ) begin
            else_else_else_else_if_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                + 12'b111111111101)));
          end
          else_else_else_else_if_land_1_lpi_dfm = else_else_else_else_if_land_1_sva_1
              & (p2planets_1_sva[0]);
          if ( else_else_else_else_if_land_1_lpi_dfm ) begin
            else_else_else_else_if_land_sva_1 = ~ (readslicef_10_1_9((({1'b1 , (~
                (vga_y_1_sva[10:2]))}) + 10'b11111)));
          end
          else_else_else_else_if_land_lpi_dfm = else_else_else_else_if_land_sva_1
              & else_else_else_else_if_land_1_lpi_dfm;
          if ( else_else_else_else_if_land_lpi_dfm ) begin
          end
          else begin
            if ( p2planets_1_sva[1] ) begin
              else_else_else_else_if_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                  + 12'b111101111101)));
            end
            else_else_else_else_if_else_land_1_lpi_dfm = else_else_else_else_if_else_land_1_sva_1
                & (p2planets_1_sva[1]);
            if ( else_else_else_else_if_else_land_1_lpi_dfm ) begin
              else_else_else_else_if_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                  , (~ (vga_y_1_sva[10:2]))}) + 10'b111111)));
            end
            else_else_else_else_if_else_land_lpi_dfm = else_else_else_else_if_else_land_sva_1
                & else_else_else_else_if_else_land_1_lpi_dfm;
            if ( else_else_else_else_if_else_land_lpi_dfm ) begin
            end
            else begin
              if ( p2planets_1_sva[2] ) begin
                else_else_else_else_if_else_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                    + 12'b111011111101)));
              end
              else_else_else_else_if_else_else_land_1_lpi_dfm = else_else_else_else_if_else_else_land_1_sva_1
                  & (p2planets_1_sva[2]);
              if ( else_else_else_else_if_else_else_land_1_lpi_dfm ) begin
                else_else_else_else_if_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                    , (~ (vga_y_1_sva[10:2]))}) + 10'b1011111)));
              end
              else_else_else_else_if_else_else_land_lpi_dfm = else_else_else_else_if_else_else_land_sva_1
                  & else_else_else_else_if_else_else_land_1_lpi_dfm;
              if ( else_else_else_else_if_else_else_land_lpi_dfm ) begin
              end
              else begin
                if ( p2planets_1_sva[3] ) begin
                  else_else_else_else_if_else_else_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                      + 12'b111001111101)));
                end
                else_else_else_else_if_else_else_else_land_1_lpi_dfm = else_else_else_else_if_else_else_else_land_1_sva_1
                    & (p2planets_1_sva[3]);
                if ( else_else_else_else_if_else_else_else_land_1_lpi_dfm ) begin
                  else_else_else_else_if_else_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                      , (~ (vga_y_1_sva[10:2]))}) + 10'b1111111)));
                end
                else_else_else_else_if_else_else_else_land_lpi_dfm = else_else_else_else_if_else_else_else_land_sva_1
                    & else_else_else_else_if_else_else_else_land_1_lpi_dfm;
                if ( else_else_else_else_if_else_else_else_land_lpi_dfm ) begin
                end
                else begin
                  if ( p2planets_1_sva[4] ) begin
                    else_else_else_else_if_else_else_else_else_land_1_sva_1 = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva)
                        + 12'b110111111101)));
                  end
                  else_else_else_else_if_else_else_else_else_land_1_lpi_dfm = else_else_else_else_if_else_else_else_else_land_1_sva_1
                      & (p2planets_1_sva[4]);
                  if ( else_else_else_else_if_else_else_else_else_land_1_lpi_dfm
                      ) begin
                    else_else_else_else_if_else_else_else_else_land_sva_1 = ~ (readslicef_10_1_9((({1'b1
                        , (~ (vga_y_1_sva[10:2]))}) + 10'b10011111)));
                  end
                  else_else_else_else_if_else_else_else_else_land_lpi_dfm = else_else_else_else_if_else_else_else_else_land_sva_1
                      & else_else_else_else_if_else_else_else_else_land_1_lpi_dfm;
                  if ( else_else_else_else_if_else_else_else_else_land_lpi_dfm )
                      begin
                  end
                  else begin
                    if ( p2planets_1_sva[5] ) begin
                      else_else_else_else_if_else_else_else_else_else_land_1_sva_1
                          = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva) +
                          12'b110101111101)));
                    end
                    else_else_else_else_if_else_else_else_else_else_land_1_lpi_dfm
                        = else_else_else_else_if_else_else_else_else_else_land_1_sva_1
                        & (p2planets_1_sva[5]);
                    if ( else_else_else_else_if_else_else_else_else_else_land_1_lpi_dfm
                        ) begin
                      else_else_else_else_if_else_else_else_else_else_land_sva_1
                          = ~ (readslicef_10_1_9((({1'b1 , (~ (vga_y_1_sva[10:2]))})
                          + 10'b10111111)));
                    end
                    else_else_else_else_if_else_else_else_else_else_land_lpi_dfm
                        = else_else_else_else_if_else_else_else_else_else_land_sva_1
                        & else_else_else_else_if_else_else_else_else_else_land_1_lpi_dfm;
                  end
                end
              end
            end
          end
        end
        begin : waitLoop3Exit
          forever begin : waitLoop3
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop3Exit;
          end
        end
        // C-Step 4 of Loop 'main'
        C1047552_30_dfmergedata_sva_19 = 30'b0;
        else_else_else_else_if_else_else_else_else_else_else_else_land_lpi_dfm =
            1'b0;
        else_else_else_else_if_else_else_else_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1 =
            1'b0;
        else_else_else_else_if_else_else_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_else_if_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_else_else_else_land_sva_1 = 1'b0;
        else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
        if ( land_lpi_dfm ) begin
        end
        else if ( else_land_lpi_dfm ) begin
        end
        else if ( else_else_land_lpi_dfm ) begin
        end
        else if ( else_else_else_land_lpi_dfm ) begin
          if ( else_else_else_if_land_lpi_dfm ) begin
          end
          else if ( else_else_else_if_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_if_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_if_else_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_if_else_else_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_if_else_else_else_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_if_else_else_else_else_else_else_land_lpi_dfm
              ) begin
          end
          else begin
            if ( p1planets_1_sva[7] ) begin
              else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1 =
                  ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva) + 12'b110001111101)));
            end
            else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm =
                else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1
                & (p1planets_1_sva[7]);
            if ( else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm
                ) begin
              else_else_else_if_else_else_else_else_else_else_else_land_sva_1 = ~
                  (readslicef_10_1_9((({1'b1 , (~ (vga_y_1_sva[10:2]))}) + 10'b11111111)));
            end
          end
        end
        else if ( else_else_else_else_land_lpi_dfm ) begin
          if ( else_else_else_else_if_land_lpi_dfm ) begin
          end
          else if ( else_else_else_else_if_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_else_if_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_else_if_else_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_else_if_else_else_else_else_land_lpi_dfm ) begin
          end
          else if ( else_else_else_else_if_else_else_else_else_else_land_lpi_dfm
              ) begin
          end
          else begin
            if ( p2planets_1_sva[6] ) begin
              else_else_else_else_if_else_else_else_else_else_else_land_1_sva_1 =
                  ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva) + 12'b110011111101)));
            end
            else_else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm =
                else_else_else_else_if_else_else_else_else_else_else_land_1_sva_1
                & (p2planets_1_sva[6]);
            if ( else_else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm
                ) begin
              else_else_else_else_if_else_else_else_else_else_else_land_sva_1 = ~
                  (readslicef_10_1_9((({1'b1 , (~ (vga_y_1_sva[10:2]))}) + 10'b11011111)));
            end
            else_else_else_else_if_else_else_else_else_else_else_land_lpi_dfm = else_else_else_else_if_else_else_else_else_else_else_land_sva_1
                & else_else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm;
            if ( else_else_else_else_if_else_else_else_else_else_else_land_lpi_dfm
                ) begin
            end
            else begin
              if ( p2planets_1_sva[7] ) begin
                else_else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1
                    = ~ (readslicef_12_1_11((conv_u2s_11_12(vga_y_1_sva) + 12'b110001111101)));
              end
              else_else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm
                  = else_else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1
                  & (p2planets_1_sva[7]);
              if ( else_else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm
                  ) begin
                else_else_else_else_if_else_else_else_else_else_else_else_land_sva_1
                    = ~ (readslicef_10_1_9((({1'b1 , (~ (vga_y_1_sva[10:2]))}) +
                    10'b11111111)));
              end
              else_else_else_else_if_else_else_else_else_else_else_else_land_lpi_dfm
                  = else_else_else_else_if_else_else_else_else_else_else_else_land_sva_1
                  & else_else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm;
            end
          end
        end
        else begin
          C1047552_30_dfmergedata_sva_19 = RGB_rsc_mgc_in_wire_d;
        end
        else_else_else_if_or_4_tmp = (else_else_else_if_else_else_else_else_else_else_else_land_sva_1
            & else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm)
            | else_else_else_if_else_else_else_else_else_else_land_lpi_dfm | else_else_else_if_else_else_else_else_else_land_lpi_dfm
            | else_else_else_if_else_else_else_else_land_lpi_dfm | else_else_else_if_else_else_else_land_lpi_dfm
            | else_else_else_if_else_else_land_lpi_dfm | else_else_else_if_else_land_lpi_dfm
            | else_else_else_if_land_lpi_dfm;
        else_else_else_else_if_or_tmp = else_else_else_else_if_else_else_else_else_else_else_else_land_lpi_dfm
            | else_else_else_else_if_else_else_else_else_else_else_land_lpi_dfm |
            else_else_else_else_if_else_else_else_else_else_land_lpi_dfm | else_else_else_else_if_else_else_else_else_land_lpi_dfm
            | else_else_else_else_if_else_else_else_land_lpi_dfm | else_else_else_else_if_else_else_land_lpi_dfm
            | else_else_else_else_if_else_land_lpi_dfm | else_else_else_else_if_land_lpi_dfm;
        C1047552_30_dfmergedata_lpi_dfm_20 = MUX1HOT_v_30_6_2({C1047552_30_dfmergedata_lpi_dfm_20
            , 30'b101010100001010101000000000000 , C1047552_30_dfmergedata_sva_19
            , 30'b111111111100000000000000000000 , 30'b1111111111 , 30'b11111111110000000000},
            {(((~ else_else_else_if_or_4_tmp) & else_else_and_m1c) | ((~ else_else_else_else_if_or_tmp)
            & else_else_else_and_m1c)) , ((else_else_else_if_or_4_tmp & else_else_and_m1c)
            | (else_else_else_else_if_or_tmp & else_else_else_and_m1c)) , and_itm
            , (else_else_land_lpi_dfm & nor_m1c) , (else_land_lpi_dfm & (~ land_lpi_dfm))
            , land_lpi_dfm});
        if ( (MUX_s_1_2_2({(else_else_else_else_if_else_else_else_else_else_else_else_land_lpi_dfm
            | else_else_else_else_if_else_else_else_else_else_else_land_lpi_dfm |
            else_else_else_else_if_else_else_else_else_else_land_lpi_dfm | else_else_else_else_if_else_else_else_else_land_lpi_dfm
            | else_else_else_else_if_else_else_else_land_lpi_dfm | else_else_else_else_if_else_else_land_lpi_dfm
            | else_else_else_else_if_else_land_lpi_dfm | else_else_else_else_if_land_lpi_dfm
            | (~ else_else_else_else_land_lpi_dfm)) , else_else_else_if_or_4_tmp},
            else_else_else_land_lpi_dfm)) | else_else_land_lpi_dfm | else_land_lpi_dfm
            | land_lpi_dfm ) begin
          RGB_o_rsc_mgc_out_stdreg_d <= C1047552_30_dfmergedata_lpi_dfm_20;
        end
        begin : waitLoop4Exit
          forever begin : waitLoop4
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop4Exit;
          end
        end
        // C-Step 5 of Loop 'main'
      end
    end
    and_itm = 1'b0;
    else_else_else_and_m1c = 1'b0;
    else_else_else_else_if_or_tmp = 1'b0;
    else_else_and_m1c = 1'b0;
    else_else_else_if_or_4_tmp = 1'b0;
    nor_m1c = 1'b0;
    C1047552_30_dfmergedata_lpi_dfm_20 = 30'b0;
    C1047552_30_dfmergedata_sva_19 = 30'b0;
    else_else_else_else_if_else_else_else_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_else_land_lpi_dfm = 1'b0;
    else_else_else_else_if_else_land_sva_1 = 1'b0;
    else_else_else_else_if_else_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_else_land_1_sva_1 = 1'b0;
    else_else_else_else_if_land_lpi_dfm = 1'b0;
    else_else_else_else_if_land_sva_1 = 1'b0;
    else_else_else_else_if_land_1_lpi_dfm = 1'b0;
    else_else_else_else_if_land_1_sva_1 = 1'b0;
    else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_else_slc_svs = 1'b0;
    else_else_else_if_else_else_else_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_land_sva_1 = 1'b0;
    else_else_else_if_else_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_if_else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_land_sva_1 = 1'b0;
    else_else_else_if_else_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_else_else_land_1_sva_1 = 1'b0;
    else_else_else_if_else_else_land_lpi_dfm = 1'b0;
    else_else_else_if_else_else_land_sva_1 = 1'b0;
    else_else_else_if_else_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_else_land_1_sva_1 = 1'b0;
    else_else_else_if_else_land_lpi_dfm = 1'b0;
    else_else_else_if_else_land_sva_1 = 1'b0;
    else_else_else_if_else_land_1_lpi_dfm = 1'b0;
    else_else_else_if_else_land_1_sva_1 = 1'b0;
    else_else_else_if_land_lpi_dfm = 1'b0;
    else_else_else_if_land_sva_1 = 1'b0;
    else_else_else_if_land_1_lpi_dfm = 1'b0;
    else_else_else_if_land_1_sva_1 = 1'b0;
    else_else_else_land_lpi_dfm = 1'b0;
    else_else_else_land_sva_1 = 1'b0;
    else_else_else_slc_svs = 1'b0;
    else_else_land_lpi_dfm = 1'b0;
    else_else_land_sva_1 = 1'b0;
    else_else_land_1_lpi_dfm = 1'b0;
    else_else_land_1_sva_1 = 1'b0;
    else_else_land_2_lpi_dfm = 1'b0;
    else_else_land_2_sva_1 = 1'b0;
    else_else_slc_svs = 1'b0;
    else_land_lpi_dfm = 1'b0;
    else_land_sva_1 = 1'b0;
    else_land_1_lpi_dfm = 1'b0;
    else_land_1_sva_1 = 1'b0;
    else_land_2_lpi_dfm = 1'b0;
    else_land_2_sva_1 = 1'b0;
    else_slc_svs = 1'b0;
    land_lpi_dfm = 1'b0;
    land_sva_1 = 1'b0;
    land_1_lpi_dfm = 1'b0;
    land_1_sva_1 = 1'b0;
    land_2_lpi_dfm = 1'b0;
    land_2_sva_1 = 1'b0;
    slc_svs = 1'b0;
    p2planets_1_sva = 8'b0;
    p1planets_1_sva = 8'b0;
    by_1_sva = 11'b0;
    bx_1_sva = 11'b0;
    p2y_1_sva = 11'b0;
    p1y_1_sva = 11'b0;
    vga_y_1_sva = 11'b0;
    vga_x_1_sva = 11'b0;
    RGB_o_rsc_mgc_out_stdreg_d <= 30'b0;
    // NOP
  end


  function [0:0] readslicef_12_1_11;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 11;
    readslicef_12_1_11 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_13_1_12;
    input [12:0] vector;
    reg [12:0] tmp;
  begin
    tmp = vector >> 12;
    readslicef_13_1_12 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_10_1_9;
    input [9:0] vector;
    reg [9:0] tmp;
  begin
    tmp = vector >> 9;
    readslicef_10_1_9 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_9_1_8;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_9_1_8 = tmp[0:0];
  end
  endfunction


  function [7:0] readslicef_12_8_4;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 4;
    readslicef_12_8_4 = tmp[7:0];
  end
  endfunction


  function [0:0] readslicef_8_1_7;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 7;
    readslicef_8_1_7 = tmp[0:0];
  end
  endfunction


  function [29:0] MUX1HOT_v_30_6_2;
    input [179:0] inputs;
    input [5:0] sel;
    reg [29:0] result;
    integer i;
  begin
    result = inputs[0+:30] & {30{sel[0]}};
    for( i = 1; i < 6; i = i + 1 )
      result = result | (inputs[i*30+:30] & {30{sel[i]}});
    MUX1HOT_v_30_6_2 = result;
  end
  endfunction


  function [0:0] MUX_s_1_2_2;
    input [1:0] inputs;
    input [0:0] sel;
    reg [0:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[1:1];
      end
      1'b1 : begin
        result = inputs[0:0];
      end
      default : begin
        result = inputs[1:1];
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function signed [11:0] conv_u2s_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_12 = {1'b0, vector};
  end
  endfunction


  function  [12:0] conv_u2u_12_13 ;
    input [11:0]  vector ;
  begin
    conv_u2u_12_13 = {1'b0, vector};
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction


  function signed [9:0] conv_u2s_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2s_9_10 = {1'b0, vector};
  end
  endfunction


  function  [8:0] conv_u2u_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_9 = {1'b0, vector};
  end
  endfunction


  function  [7:0] conv_u2u_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_8 = {1'b0, vector};
  end
  endfunction


  function signed [10:0] conv_u2s_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_11 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    ImageUnit
//  Generated from file(s):
//    2) $PROJECT_HOME/drawscreen.c
// ------------------------------------------------------------------


module ImageUnit (
  vga_x_rsc_z, vga_y_rsc_z, p1y_rsc_z, p2y_rsc_z, bx_rsc_z, by_rsc_z, p1planets_rsc_z,
      p2planets_rsc_z, RGB_rsc_z, RGB_o_rsc_z, clk, en, arst_n
);
  input [10:0] vga_x_rsc_z;
  input [10:0] vga_y_rsc_z;
  input [10:0] p1y_rsc_z;
  input [10:0] p2y_rsc_z;
  input [10:0] bx_rsc_z;
  input [10:0] by_rsc_z;
  input [7:0] p1planets_rsc_z;
  input [7:0] p2planets_rsc_z;
  input [29:0] RGB_rsc_z;
  output [29:0] RGB_o_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [10:0] vga_x_rsc_mgc_in_wire_d;
  wire [10:0] vga_y_rsc_mgc_in_wire_d;
  wire [10:0] p1y_rsc_mgc_in_wire_d;
  wire [10:0] p2y_rsc_mgc_in_wire_d;
  wire [10:0] bx_rsc_mgc_in_wire_d;
  wire [10:0] by_rsc_mgc_in_wire_d;
  wire [7:0] p1planets_rsc_mgc_in_wire_d;
  wire [7:0] p2planets_rsc_mgc_in_wire_d;
  wire [29:0] RGB_rsc_mgc_in_wire_d;
  wire [29:0] RGB_o_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire #(.rscid(1),
  .width(11)) vga_x_rsc_mgc_in_wire (
      .d(vga_x_rsc_mgc_in_wire_d),
      .z(vga_x_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(11)) vga_y_rsc_mgc_in_wire (
      .d(vga_y_rsc_mgc_in_wire_d),
      .z(vga_y_rsc_z)
    );
  mgc_in_wire #(.rscid(3),
  .width(11)) p1y_rsc_mgc_in_wire (
      .d(p1y_rsc_mgc_in_wire_d),
      .z(p1y_rsc_z)
    );
  mgc_in_wire #(.rscid(4),
  .width(11)) p2y_rsc_mgc_in_wire (
      .d(p2y_rsc_mgc_in_wire_d),
      .z(p2y_rsc_z)
    );
  mgc_in_wire #(.rscid(5),
  .width(11)) bx_rsc_mgc_in_wire (
      .d(bx_rsc_mgc_in_wire_d),
      .z(bx_rsc_z)
    );
  mgc_in_wire #(.rscid(6),
  .width(11)) by_rsc_mgc_in_wire (
      .d(by_rsc_mgc_in_wire_d),
      .z(by_rsc_z)
    );
  mgc_in_wire #(.rscid(7),
  .width(8)) p1planets_rsc_mgc_in_wire (
      .d(p1planets_rsc_mgc_in_wire_d),
      .z(p1planets_rsc_z)
    );
  mgc_in_wire #(.rscid(8),
  .width(8)) p2planets_rsc_mgc_in_wire (
      .d(p2planets_rsc_mgc_in_wire_d),
      .z(p2planets_rsc_z)
    );
  mgc_in_wire #(.rscid(9),
  .width(30)) RGB_rsc_mgc_in_wire (
      .d(RGB_rsc_mgc_in_wire_d),
      .z(RGB_rsc_z)
    );
  mgc_out_stdreg #(.rscid(10),
  .width(30)) RGB_o_rsc_mgc_out_stdreg (
      .d(RGB_o_rsc_mgc_out_stdreg_d),
      .z(RGB_o_rsc_z)
    );
  ImageUnit_core ImageUnit_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vga_x_rsc_mgc_in_wire_d(vga_x_rsc_mgc_in_wire_d),
      .vga_y_rsc_mgc_in_wire_d(vga_y_rsc_mgc_in_wire_d),
      .p1y_rsc_mgc_in_wire_d(p1y_rsc_mgc_in_wire_d),
      .p2y_rsc_mgc_in_wire_d(p2y_rsc_mgc_in_wire_d),
      .bx_rsc_mgc_in_wire_d(bx_rsc_mgc_in_wire_d),
      .by_rsc_mgc_in_wire_d(by_rsc_mgc_in_wire_d),
      .p1planets_rsc_mgc_in_wire_d(p1planets_rsc_mgc_in_wire_d),
      .p2planets_rsc_mgc_in_wire_d(p2planets_rsc_mgc_in_wire_d),
      .RGB_rsc_mgc_in_wire_d(RGB_rsc_mgc_in_wire_d),
      .RGB_o_rsc_mgc_out_stdreg_d(RGB_o_rsc_mgc_out_stdreg_d)
    );
endmodule



