directive set /ImageUnit/ImageUnit:core/ImageUnit:core:conc/if:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /ImageUnit/ImageUnit:core/ImageUnit:core:conc/else:else:else:if:aif:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /ImageUnit/ImageUnit:core/ImageUnit:core:conc/else:else:else:if:else:else:else:else:else:else:else:aif:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,11,1,12)
directive set /ImageUnit/ImageUnit:core/ImageUnit:core:conc/else:else:else:if:if:acc#1 RESOURCE_NAME else:else:else:if:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(10,0,9,1,10)
directive set /ImageUnit/ImageUnit:core/ImageUnit:core:conc/else:else:else:if:else:else:else:else:else:else:else:if:acc#1 RESOURCE_NAME else:else:else:if:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(10,0,9,1,10)
